import json, glob, random
from datetime import datetime
from pprint import pprint as pp

NAME = "Crypto Robo"
DESC = "100 Pure Art of Super Cool Robots. Now available on Arbitrum One L2 Blockchain. This collection was generated by AI with love 🤖❤️"
IMG = "https://diewland.github.io/crypto-robo/assets/{}"
ENGINE = "Jigsaw Engine"

SRC_PATH = "./temp/*/*/*/*"
OUTPUT_DIR = "./json"
MAX_SUPPLY = 100
SHUFFLE_TIME = 99

# extract raw data
raw = []
for file in glob.glob(SRC_PATH):
    # [ scene, class, power, img ]
    raw.append(file.split('/')[2:])
    
# shuffle
for rnd in range(1, SHUFFLE_TIME+1):
    random.shuffle(raw)

#pp(raw)
#exit()

# build chunk
chunk = []
for id, r in enumerate(raw):
    (scene, clz, power, img) = r

    # debug
    print(id, r)

    # template
    metadata = {
      "name": "***",
      "description": DESC,
      "image": "***",
      "attributes": [
        {
          "trait_type": "Scene",
          "value": "***",
        },
        {
          "trait_type": "Class",
          "value": "***",
        },
        {
          "trait_type": "Power Source",
          "value": "***",
        },
      ],
      "compiler": ENGINE,
    }

    # update data
    metadata["name"] = "{} #{}".format(NAME, id)
    metadata["image"] = IMG.format(img)
    metadata["attributes"][0]["value"] = scene
    metadata["attributes"][1]["value"] = clz
    metadata["attributes"][2]["value"] = power

    # add to chunk
    chunk.append(metadata)

#pp(chunk)

# write file
for id, metadata in enumerate(chunk):
    with open("./{}/{}.json".format(OUTPUT_DIR, id), "w") as f:
        json.dump(metadata, f, ensure_ascii=False)
